
package ihe.iti.xds_b._2010;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import oasis.names.tc.ebxml_regrep.xsd.lcm._3.RemoveObjectsRequestType;
import oasis.names.tc.ebxml_regrep.xsd.rs._3.RegistryResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "XDSDeletetWS", targetNamespace = "urn:ihe:iti:xds-b:2010")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
//    ihe.iti.xds_b._2007.ObjectFactory.class,
    ihe.iti.xds_b._2010.ObjectFactory.class,
    oasis.names.tc.ebxml_regrep.xsd.lcm._3.ObjectFactory.class,
    oasis.names.tc.ebxml_regrep.xsd.rim._3.ObjectFactory.class,
    oasis.names.tc.ebxml_regrep.xsd.rs._3.ObjectFactory.class,
    org.w3._2004._08.xop.include.ObjectFactory.class
})
public interface XDSDeletetWS {


    /**
     * 
     * @param body0
     * @param body
     */
    @WebMethod(operationName = "DocumentRegistry_DeleteDocumentSet")
    public void documentRegistryDeleteDocumentSet(
        @WebParam(name = "RemoveObjectsRequest", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0", partName = "body")
        RemoveObjectsRequestType body,
        @WebParam(name = "RegistryResponse", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0", mode = WebParam.Mode.OUT, partName = "body")
        Holder<RegistryResponseType> body0);

}
